'use client'

import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const translations = {
  fr: {
    // Navbar
    nav: {
      home: 'Accueil',
      studybox: 'StudyBox',
      news: 'Actualités',
      application: 'Application',
      about: 'À propos',
      partners: 'Nos partenaires',
      contact: 'Contact',
      buy: 'Acheter',
      search: 'Rechercher...',
      // StudyBox menu
      discover: 'Découvrir',
      theStudybox: 'La StudyBox',
      whatContains: 'Que contient la box ?',
      forWho: 'Pour qui ?',
      pricing: 'Tarifs',
      buyMenu: 'Acheter',
      orderNow: 'Commander maintenant',
      offersPromo: 'Offres & promotions',
      deliveryReturns: 'Livraison & retours',
      paymentMethods: 'Moyens de paiement',
      whyStudybox: 'Pourquoi StudyBox',
      ourAdvantages: 'Nos avantages',
      qualityCommitment: 'Qualité & engagement',
      studentTestimonials: 'Témoignages étudiants',
      // News menu
      blogArticles: 'Blog & Articles',
      allNews: 'Toutes les actualités',
      studyTips: 'Conseils pour étudier',
      organizationProductivity: 'Organisation & productivité',
      studentLife: 'Vie étudiante',
      events: 'Événements',
      eventsAgenda: 'Agenda des événements',
      marketsFairs: 'Marchés & salons',
      studentMeetings: 'Rencontres étudiantes',
      workshopsMenu: 'Ateliers & workshops',
      whatsNew: 'Nouveautés',
      newProducts: 'Nouveaux produits',
      appUpdates: 'Mises à jour app',
      newPartners: 'Nouveaux partenaires',
      // Application menu
      download: 'Télécharger',
      theApp: "L'application StudyBox",
      downloadIOS: 'Télécharger sur iOS',
      downloadAndroid: 'Télécharger sur Android',
      webVersion: 'Version web',
      features: 'Fonctionnalités',
      courseOrganization: 'Organisation des cours',
      planningReminders: 'Planning & rappels',
      noteTaking: 'Prise de notes',
      sharingCollab: 'Partage & collaboration',
      helpTutorials: 'Aide & Tutoriels',
      gettingStarted: 'Guide de démarrage',
      videoTutorials: 'Tutoriels vidéo',
      tipsAdvice: 'Astuces & conseils',
      reportProblem: 'Signaler un problème',
      suggestFeature: 'Suggérer une fonctionnalité',
      // About menu
      ourCompany: 'Notre entreprise',
      whoAreWe: 'Qui sommes-nous ?',
      ourHistory: 'Notre histoire',
      theTeam: "L'équipe",
      ourVision: 'Notre vision',
      ourValues: 'Nos valeurs',
      ourMission: 'Notre mission',
      ourValuesMenu: 'Nos valeurs',
      ourCommitments: 'Nos engagements',
      communityMenu: 'Communauté',
      ourPartners: 'Nos partenaires',
      contactUs: 'Nous contacter',
      faqSupport: 'FAQ & Support',
      faq: 'Questions fréquentes',
      supportSav: 'Support & SAV',
      // Partners menu
      allPartners: 'Tous nos partenaires',
      restaurant: 'Restauration',
      sportsLeisure: 'Sports & Loisirs',
      studentServices: 'Services étudiants',
      becomePartner: 'Devenir partenaire',
      whyJoinUs: 'Pourquoi nous rejoindre',
      partnerAdvantages: 'Avantages partenaires',
      submitApplication: 'Déposer une candidature',
      proPontact: 'Contact professionnel',
      specialOffers: 'Offres spéciales',
      studentOffers: 'Offres étudiants',
      exclusiveDiscounts: 'Réductions exclusives',
      promoCode: 'Code promo',
      // Contact menu
      getInTouch: 'Nous joindre',
      contactForm: 'Formulaire de contact',
      emailUs: 'Nous écrire',
      callUs: 'Nous appeler',
      findUs: 'Nous trouver',
      socialMedia: 'Réseaux sociaux',
      followInstagram: 'Suivez-nous sur Instagram',
      followFacebook: 'Suivez-nous sur Facebook',
      followLinkedin: 'Suivez-nous sur LinkedIn',
      proServices: 'Services pro',
      partnerships: 'Partenariats',
      pressMedia: 'Presse & médias',
      careers: 'Carrières',
    },
    // Hero
    hero: {
      title: 'StudyBox',
      subtitle: "L'outil complet pour réussir.",
      description: 'Tout ce dont vous avez besoin, organisé avec élégance.',
      cta: 'Découvrir',
    },
    // Home page
    home: {
      productTitle: 'Pensée pour les étudiants',
      productSubtitle: 'Élégante. Utile. Essentielle.',
      imagePlaceholder: 'Image placeholder',
      everythingTitle: 'Tout ce dont vous avez besoin',
      everythingSubtitle: 'Organisée. Pratique. Élégante.',
      premiumQuality: 'Qualité premium',
      optimalOrganization: 'Organisation optimale',
      modernDesign: 'Design moderne',
      carefulDelivery: 'Livraison soignée',
      startingFrom: 'À partir de',
      buyButton: 'Acheter',
      craftedTitle: 'Conçue avec soin',
      craftedSubtitle: "Chaque détail compte pour offrir une expérience d'étude optimale.",
      superiorQuality: 'Qualité supérieure',
      superiorQualityDesc: 'Des matériaux durables et élégants pour une utilisation quotidienne.',
      timeSaving: 'Gain de temps',
      timeSavingDesc: "Tout est organisé et prêt à l'emploi pour vos études.",
      madeWithPassion: 'Fait avec passion',
      madeWithPassionDesc: 'Chaque box est préparée avec attention pour votre réussite.',
    },
    // About page
    about: {
      title: 'À propos',
      subtitle: "Trois étudiants, une mission : révolutionner l'expérience étudiante.",
      historyTitle: 'Notre histoire',
      historyP1: "StudyBox est née d'un constat simple : les étudiants méritent mieux. En tant qu'étudiants nous-mêmes, nous avons vécu les défis du quotidien académique.",
      historyP2: "C'est en 2024 que l'idée a germé. Trois amis passionnés ont décidé de créer une solution complète pour accompagner les étudiants dans leur parcours.",
      historyP3: "Aujourd'hui, StudyBox c'est bien plus qu'une box : c'est un écosystème pensé pour la réussite.",
      teamPhoto: "Photo de l'équipe",
      missionTitle: 'Notre mission',
      missionSubtitle: 'Simplifier la vie étudiante, un étudiant à la fois.',
      innovation: 'Innovation',
      innovationDesc: 'Repenser constamment nos solutions pour répondre aux besoins réels des étudiants.',
      passion: 'Passion',
      passionDesc: 'Chaque box est préparée avec soin et attention pour votre réussite.',
      community: 'Communauté',
      communityDesc: "Créer un réseau solidaire d'étudiants et de partenaires engagés.",
      teamTitle: "L'équipe",
      teamSubtitle: 'Trois étudiants entrepreneurs unis par une même vision.',
      cofounder: 'Co-fondateur',
      valuesTitle: 'Nos valeurs',
      quality: 'Qualité',
      qualityDesc: 'Nous sélectionnons avec soin chaque produit pour garantir une expérience premium à nos étudiants.',
      accessibility: 'Accessibilité',
      accessibilityDesc: 'Des prix justes pour que chaque étudiant puisse bénéficier de nos solutions.',
      proximity: 'Proximité',
      proximityDesc: 'Nous privilégions les partenaires locaux et les circuits courts pour un impact positif.',
      reactivity: 'Réactivité',
      reactivityDesc: "À l'écoute de vos retours pour améliorer constamment notre offre et nos services.",
      visionTitle: 'Notre vision',
      visionSubtitle: "Devenir la référence de l'accompagnement étudiant en Belgique.",
      visionP1: "Notre ambition est simple : que chaque étudiant puisse accéder aux outils et ressources nécessaires à sa réussite, sans compromis sur la qualité.",
      visionP2: "Nous croyons en un modèle où les entreprises locales et les étudiants grandissent ensemble, créant un écosystème bénéfique pour tous.",
      visionP3: "D'ici les prochaines années, nous souhaitons étendre notre réseau de partenaires et proposer des solutions toujours plus adaptées aux besoins des étudiants.",
      responsibleGrowth: 'Croissance responsable',
      responsibleGrowthDesc: 'Grandir tout en restant fidèles à nos valeurs',
      localImpact: 'Impact local',
      localImpactDesc: "Soutenir l'économie locale et les commerces de proximité",
      studentCommunity: 'Communauté étudiante',
      studentCommunityDesc: 'Créer des liens durables entre étudiants',
      commitmentsTitle: 'Nos engagements',
      commitmentsSubtitle: 'Ce que nous promettons à chaque étudiant.',
      guaranteedQuality: 'Qualité garantie',
      guaranteedQualityDesc: 'Chaque produit est sélectionné avec soin pour répondre à vos attentes.',
      reactiveSupport: 'Support réactif',
      reactiveSupportDesc: 'Une équipe à votre écoute pour répondre à toutes vos questions.',
      fastDelivery: 'Livraison rapide',
      fastDeliveryDesc: 'Recevez votre StudyBox dans les meilleurs délais.',
      ctaTitle: "Rejoignez l'aventure StudyBox",
      ctaSubtitle: 'Découvrez comment nous pouvons vous accompagner dans votre réussite.',
      discoverStudybox: 'Découvrir la StudyBox',
      contactUs: 'Nous contacter',
    },
    // Order page
    order: {
      title: 'Commander votre StudyBox',
      subtitle: 'Quelques étapes pour recevoir votre box étudiante',
      step1: 'Produit',
      step2: 'Livraison',
      step3: 'Paiement',
      step4: 'Confirmation',
      chooseStudybox: 'Choisissez votre StudyBox',
      classicStudybox: 'StudyBox Classique',
      classicDesc: "La box complète pour réussir vos études. Contient tout le nécessaire pour une session d'étude productive.",
      perBox: '/ box',
      quantity: 'Quantité',
      giftWrap: 'Emballage cadeau',
      giftWrapDesc: 'Votre StudyBox sera emballée dans un joli papier cadeau avec un ruban.',
      giftMessage: 'Message personnalisé (optionnel)',
      giftMessagePlaceholder: 'Écrivez votre message ici...',
      freeShipping: 'Livraison gratuite à partir de 3 StudyBox commandées !',
      continue: 'Continuer',
      back: 'Retour',
      deliveryInfo: 'Informations de livraison',
      yourDetails: 'Vos coordonnées',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      deliveryAddress: 'Adresse de livraison',
      address: 'Adresse',
      postalCode: 'Code postal',
      city: 'Ville',
      country: 'Pays',
      deliveryEstimate: 'Livraison estimée sous 3-5 jours ouvrables en Belgique.',
      paymentMethod: 'Mode de paiement',
      creditCard: 'Carte bancaire',
      creditCardDesc: 'Visa, Mastercard, Bancontact',
      bancontact: 'Bancontact',
      bancontactDesc: 'Paiement sécurisé via Bancontact',
      paypal: 'PayPal',
      paypalDesc: 'Paiement via votre compte PayPal',
      bankTransfer: 'Virement bancaire',
      bankTransferDesc: 'Commande expédiée après réception du paiement',
      securePayment: 'Paiement 100% sécurisé',
      securePaymentDesc: 'Vos données sont protégées par un cryptage SSL.',
      acceptTerms: "J'accepte les",
      termsOfSale: 'conditions générales de vente',
      and: 'et la',
      privacyPolicy: 'politique de confidentialité',
      pay: 'Payer',
      thankYou: 'Merci pour votre commande !',
      confirmationMsg: 'Votre commande a été confirmée. Vous recevrez un email de confirmation à',
      summary: 'Récapitulatif',
      orderNumber: 'Numéro de commande',
      shipping: 'Livraison',
      free: 'Gratuite',
      total: 'Total',
      backToHome: "Retour à l'accueil",
      question: 'Une question ?',
      promoCode: 'Code promo',
      apply: 'Appliquer',
      securePaymentBadge: 'Paiement sécurisé',
      fastDeliveryBadge: 'Livraison rapide',
      satisfiedBadge: 'Satisfait ou remboursé',
    },
    // Application page
    app: {
      heroTitle: 'StudyBox',
      heroSubtitle: "L'application mobile",
      heroDesc: "Votre compagnon d'études intelligent. Toujours avec vous.",
      download: 'Télécharger',
      learnMore: 'En savoir plus',
      scrollDemo: "Scrollez sur l'écran pour voir la démo",
      organizeTitle: 'Organisez vos études',
      organizeDesc: 'Planifiez vos révisions, suivez vos progrès et atteignez vos objectifs académiques avec facilité.',
      smartPlanning: 'Planning intelligent',
      smartPlanningDesc: 'Créez votre emploi du temps personnalisé',
      progressTracking: 'Suivi de progression',
      progressTrackingDesc: 'Visualisez vos résultats en temps réel',
      customReminders: 'Rappels personnalisés',
      customRemindersDesc: 'Ne manquez plus jamais une échéance',
      reviseTitle: 'Révisez efficacement',
      reviseDesc: 'Des outils puissants pour maximiser votre apprentissage et mémoriser durablement.',
      flashcards: 'Fiches de révision',
      flashcardsDesc: 'Créez et organisez vos fiches facilement',
      quizzes: 'Quiz interactifs',
      quizzesDesc: 'Testez vos connaissances régulièrement',
      offlineMode: 'Mode hors ligne',
      offlineModeDesc: 'Étudiez partout, même sans connexion',
      successTitle: 'Conçue pour la réussite',
      successDesc: 'Une expérience utilisateur pensée dans les moindres détails',
      satisfaction: 'Satisfaction utilisateurs',
      activeStudents: 'Étudiants actifs',
      avgRating: 'Note moyenne',
      ultraFast: 'Ultra rapide',
      ultraFastDesc: 'Performance optimale sur tous les appareils',
      secure: 'Sécurisée',
      secureDesc: 'Vos données sont protégées et privées',
      customizable: 'Personnalisable',
      customizableDesc: "Adaptez l'app à vos besoins",
      sync: 'Synchronisation',
      syncDesc: 'Accédez à vos données partout',
      ctaTitle: 'Prêt à exceller ?',
      ctaDesc: "Rejoignez des milliers d'étudiants qui réussissent avec StudyBox",
      availableOn: 'Disponible sur iOS et Android',
    },
    // Partners page
    partners: {
      title: 'Nos partenaires',
      subtitle: 'Ensemble pour la réussite étudiante',
      allPartners: 'Tous nos partenaires',
      discover: 'Découvrez les établissements et entreprises qui collaborent avec StudyBox',
      restaurant: 'Restauration',
      sports: 'Sports & Loisirs',
      services: 'Services étudiants',
      visitSite: 'Visiter le site',
    },
    // Footer
    footer: {
      products: 'Produits',
      company: 'Entreprise',
      about: 'À propos',
      contact: 'Contact',
      legal: 'Légal',
      terms: 'CGV',
      privacy: 'Confidentialité',
      allRights: 'Tous droits réservés.',
    },
    // Team descriptions
    team: {
      timeo: "Passionné par l'entrepreneuriat et l'innovation au service des étudiants.",
      nathan: 'Engagé pour créer des solutions pratiques qui facilitent le quotidien étudiant.',
      valentin: 'Déterminé à accompagner chaque étudiant vers la réussite académique.',
    },
    // Feedback forms
    feedback: {
      reportProblemTitle: 'Signaler un problème',
      reportProblemDesc: 'Vous avez rencontré un bug ou un dysfonctionnement ? Décrivez-le nous pour que nous puissions l\'améliorer.',
      suggestFeatureTitle: 'Suggérer une fonctionnalité',
      suggestFeatureDesc: 'Vous avez une idée pour améliorer l\'application ? Partagez-la avec nous !',
      emailLabel: 'Votre adresse email',
      emailPlaceholder: 'exemple@email.com',
      problemLabel: 'Décrivez le problème rencontré',
      problemPlaceholder: 'Décrivez le problème en détail : que faisiez-vous, que s\'est-il passé, quel était le résultat attendu...',
      suggestionLabel: 'Décrivez votre suggestion',
      suggestionPlaceholder: 'Décrivez votre idée de fonctionnalité : à quoi servirait-elle, comment l\'imaginez-vous...',
      sendButton: 'Envoyer',
      sending: 'Envoi en cours...',
      successMessage: 'Merci ! Votre message a bien été envoyé. Nous vous répondrons rapidement.',
      errorMessage: 'Une erreur est survenue. Veuillez réessayer plus tard.',
    },
  },
  en: {
    // Navbar
    nav: {
      home: 'Home',
      studybox: 'StudyBox',
      news: 'News',
      application: 'App',
      about: 'About',
      partners: 'Partners',
      contact: 'Contact',
      buy: 'Buy',
      search: 'Search...',
      // StudyBox menu
      discover: 'Discover',
      theStudybox: 'The StudyBox',
      whatContains: 'What does the box contain?',
      forWho: 'For whom?',
      pricing: 'Pricing',
      buyMenu: 'Buy',
      orderNow: 'Order now',
      offersPromo: 'Offers & promotions',
      deliveryReturns: 'Delivery & returns',
      paymentMethods: 'Payment methods',
      whyStudybox: 'Why StudyBox',
      ourAdvantages: 'Our advantages',
      qualityCommitment: 'Quality & commitment',
      studentTestimonials: 'Student testimonials',
      // News menu
      blogArticles: 'Blog & Articles',
      allNews: 'All news',
      studyTips: 'Study tips',
      organizationProductivity: 'Organization & productivity',
      studentLife: 'Student life',
      events: 'Events',
      eventsAgenda: 'Events calendar',
      marketsFairs: 'Markets & fairs',
      studentMeetings: 'Student meetings',
      workshopsMenu: 'Workshops',
      whatsNew: "What's new",
      newProducts: 'New products',
      appUpdates: 'App updates',
      newPartners: 'New partners',
      // Application menu
      download: 'Download',
      theApp: 'The StudyBox App',
      downloadIOS: 'Download on iOS',
      downloadAndroid: 'Download on Android',
      webVersion: 'Web version',
      features: 'Features',
      courseOrganization: 'Course organization',
      planningReminders: 'Planning & reminders',
      noteTaking: 'Note taking',
      sharingCollab: 'Sharing & collaboration',
      helpTutorials: 'Help & Tutorials',
      gettingStarted: 'Getting started',
      videoTutorials: 'Video tutorials',
      tipsAdvice: 'Tips & advice',
      reportProblem: 'Report a problem',
      suggestFeature: 'Suggest a feature',
      // About menu
      ourCompany: 'Our company',
      whoAreWe: 'Who are we?',
      ourHistory: 'Our history',
      theTeam: 'The team',
      ourVision: 'Our vision',
      ourValues: 'Our values',
      ourMission: 'Our mission',
      ourValuesMenu: 'Our values',
      ourCommitments: 'Our commitments',
      communityMenu: 'Community',
      ourPartners: 'Our partners',
      contactUs: 'Contact us',
      faqSupport: 'FAQ & Support',
      faq: 'FAQ',
      supportSav: 'Support',
      // Partners menu
      allPartners: 'All our partners',
      restaurant: 'Food & Dining',
      sportsLeisure: 'Sports & Leisure',
      studentServices: 'Student services',
      becomePartner: 'Become a partner',
      whyJoinUs: 'Why join us',
      partnerAdvantages: 'Partner benefits',
      submitApplication: 'Submit application',
      proContact: 'Professional contact',
      specialOffers: 'Special offers',
      studentOffers: 'Student offers',
      exclusiveDiscounts: 'Exclusive discounts',
      promoCode: 'Promo code',
      // Contact menu
      getInTouch: 'Get in touch',
      contactForm: 'Contact form',
      emailUs: 'Email us',
      callUs: 'Call us',
      findUs: 'Find us',
      socialMedia: 'Social media',
      followInstagram: 'Follow us on Instagram',
      followFacebook: 'Follow us on Facebook',
      followLinkedin: 'Follow us on LinkedIn',
      proServices: 'Pro services',
      partnerships: 'Partnerships',
      pressMedia: 'Press & media',
      careers: 'Careers',
    },
    // Hero
    hero: {
      title: 'StudyBox',
      subtitle: 'The complete tool for success.',
      description: 'Everything you need, elegantly organized.',
      cta: 'Discover',
    },
    // Home page
    home: {
      productTitle: 'Designed for students',
      productSubtitle: 'Elegant. Useful. Essential.',
      imagePlaceholder: 'Image placeholder',
      everythingTitle: 'Everything you need',
      everythingSubtitle: 'Organized. Practical. Elegant.',
      premiumQuality: 'Premium quality',
      optimalOrganization: 'Optimal organization',
      modernDesign: 'Modern design',
      carefulDelivery: 'Careful delivery',
      startingFrom: 'Starting from',
      buyButton: 'Buy',
      craftedTitle: 'Crafted with care',
      craftedSubtitle: 'Every detail matters to provide an optimal study experience.',
      superiorQuality: 'Superior quality',
      superiorQualityDesc: 'Durable and elegant materials for daily use.',
      timeSaving: 'Time saving',
      timeSavingDesc: 'Everything is organized and ready to use for your studies.',
      madeWithPassion: 'Made with passion',
      madeWithPassionDesc: 'Each box is prepared with care for your success.',
    },
    // About page
    about: {
      title: 'About',
      subtitle: 'Three students, one mission: revolutionize the student experience.',
      historyTitle: 'Our story',
      historyP1: 'StudyBox was born from a simple observation: students deserve better. As students ourselves, we experienced the challenges of academic daily life.',
      historyP2: "It was in 2024 that the idea took shape. Three passionate friends decided to create a complete solution to support students in their journey.",
      historyP3: "Today, StudyBox is much more than a box: it's an ecosystem designed for success.",
      teamPhoto: 'Team photo',
      missionTitle: 'Our mission',
      missionSubtitle: 'Simplifying student life, one student at a time.',
      innovation: 'Innovation',
      innovationDesc: 'Constantly rethinking our solutions to meet the real needs of students.',
      passion: 'Passion',
      passionDesc: 'Each box is prepared with care and attention for your success.',
      community: 'Community',
      communityDesc: 'Creating a supportive network of students and committed partners.',
      teamTitle: 'The team',
      teamSubtitle: 'Three student entrepreneurs united by a common vision.',
      cofounder: 'Co-founder',
      valuesTitle: 'Our values',
      quality: 'Quality',
      qualityDesc: 'We carefully select each product to guarantee a premium experience for our students.',
      accessibility: 'Accessibility',
      accessibilityDesc: 'Fair prices so every student can benefit from our solutions.',
      proximity: 'Proximity',
      proximityDesc: 'We favor local partners and short circuits for a positive impact.',
      reactivity: 'Reactivity',
      reactivityDesc: 'Listening to your feedback to constantly improve our offer and services.',
      visionTitle: 'Our vision',
      visionSubtitle: 'Becoming the reference for student support in Belgium.',
      visionP1: 'Our ambition is simple: that every student can access the tools and resources necessary for their success, without compromising on quality.',
      visionP2: 'We believe in a model where local businesses and students grow together, creating a beneficial ecosystem for all.',
      visionP3: 'In the coming years, we want to expand our partner network and offer solutions that are always more adapted to student needs.',
      responsibleGrowth: 'Responsible growth',
      responsibleGrowthDesc: 'Growing while staying true to our values',
      localImpact: 'Local impact',
      localImpactDesc: 'Supporting the local economy and neighborhood businesses',
      studentCommunity: 'Student community',
      studentCommunityDesc: 'Creating lasting bonds between students',
      commitmentsTitle: 'Our commitments',
      commitmentsSubtitle: 'What we promise to every student.',
      guaranteedQuality: 'Guaranteed quality',
      guaranteedQualityDesc: 'Each product is carefully selected to meet your expectations.',
      reactiveSupport: 'Reactive support',
      reactiveSupportDesc: 'A team ready to answer all your questions.',
      fastDelivery: 'Fast delivery',
      fastDeliveryDesc: 'Receive your StudyBox as quickly as possible.',
      ctaTitle: 'Join the StudyBox adventure',
      ctaSubtitle: 'Discover how we can support you in your success.',
      discoverStudybox: 'Discover StudyBox',
      contactUs: 'Contact us',
    },
    // Order page
    order: {
      title: 'Order your StudyBox',
      subtitle: 'A few steps to receive your student box',
      step1: 'Product',
      step2: 'Delivery',
      step3: 'Payment',
      step4: 'Confirmation',
      chooseStudybox: 'Choose your StudyBox',
      classicStudybox: 'Classic StudyBox',
      classicDesc: 'The complete box for successful studies. Contains everything you need for a productive study session.',
      perBox: '/ box',
      quantity: 'Quantity',
      giftWrap: 'Gift wrapping',
      giftWrapDesc: 'Your StudyBox will be wrapped in beautiful gift paper with a ribbon.',
      giftMessage: 'Personalized message (optional)',
      giftMessagePlaceholder: 'Write your message here...',
      freeShipping: 'Free shipping from 3 StudyBox ordered!',
      continue: 'Continue',
      back: 'Back',
      deliveryInfo: 'Delivery information',
      yourDetails: 'Your details',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      deliveryAddress: 'Delivery address',
      address: 'Address',
      postalCode: 'Postal code',
      city: 'City',
      country: 'Country',
      deliveryEstimate: 'Estimated delivery within 3-5 business days in Belgium.',
      paymentMethod: 'Payment method',
      creditCard: 'Credit card',
      creditCardDesc: 'Visa, Mastercard, Bancontact',
      bancontact: 'Bancontact',
      bancontactDesc: 'Secure payment via Bancontact',
      paypal: 'PayPal',
      paypalDesc: 'Payment via your PayPal account',
      bankTransfer: 'Bank transfer',
      bankTransferDesc: 'Order shipped after payment received',
      securePayment: '100% secure payment',
      securePaymentDesc: 'Your data is protected by SSL encryption.',
      acceptTerms: 'I accept the',
      termsOfSale: 'terms and conditions',
      and: 'and the',
      privacyPolicy: 'privacy policy',
      pay: 'Pay',
      thankYou: 'Thank you for your order!',
      confirmationMsg: 'Your order has been confirmed. You will receive a confirmation email at',
      summary: 'Summary',
      orderNumber: 'Order number',
      shipping: 'Shipping',
      free: 'Free',
      total: 'Total',
      backToHome: 'Back to home',
      question: 'Any question?',
      promoCode: 'Promo code',
      apply: 'Apply',
      securePaymentBadge: 'Secure payment',
      fastDeliveryBadge: 'Fast delivery',
      satisfiedBadge: 'Satisfied or refunded',
    },
    // Application page
    app: {
      heroTitle: 'StudyBox',
      heroSubtitle: 'The mobile app',
      heroDesc: 'Your intelligent study companion. Always with you.',
      download: 'Download',
      learnMore: 'Learn more',
      scrollDemo: 'Scroll on the screen to see the demo',
      organizeTitle: 'Organize your studies',
      organizeDesc: 'Plan your revisions, track your progress and achieve your academic goals with ease.',
      smartPlanning: 'Smart planning',
      smartPlanningDesc: 'Create your personalized schedule',
      progressTracking: 'Progress tracking',
      progressTrackingDesc: 'Visualize your results in real time',
      customReminders: 'Custom reminders',
      customRemindersDesc: 'Never miss a deadline again',
      reviseTitle: 'Revise efficiently',
      reviseDesc: 'Powerful tools to maximize your learning and memorize durably.',
      flashcards: 'Flashcards',
      flashcardsDesc: 'Create and organize your cards easily',
      quizzes: 'Interactive quizzes',
      quizzesDesc: 'Test your knowledge regularly',
      offlineMode: 'Offline mode',
      offlineModeDesc: 'Study anywhere, even without connection',
      successTitle: 'Designed for success',
      successDesc: 'A user experience thought out in every detail',
      satisfaction: 'User satisfaction',
      activeStudents: 'Active students',
      avgRating: 'Average rating',
      ultraFast: 'Ultra fast',
      ultraFastDesc: 'Optimal performance on all devices',
      secure: 'Secure',
      secureDesc: 'Your data is protected and private',
      customizable: 'Customizable',
      customizableDesc: 'Adapt the app to your needs',
      sync: 'Synchronization',
      syncDesc: 'Access your data anywhere',
      ctaTitle: 'Ready to excel?',
      ctaDesc: 'Join thousands of students who succeed with StudyBox',
      availableOn: 'Available on iOS and Android',
    },
    // Partners page
    partners: {
      title: 'Our partners',
      subtitle: 'Together for student success',
      allPartners: 'All our partners',
      discover: 'Discover the establishments and companies that collaborate with StudyBox',
      restaurant: 'Food & Dining',
      sports: 'Sports & Leisure',
      services: 'Student services',
      visitSite: 'Visit website',
    },
    // Footer
    footer: {
      products: 'Products',
      company: 'Company',
      about: 'About',
      contact: 'Contact',
      legal: 'Legal',
      terms: 'Terms',
      privacy: 'Privacy',
      allRights: 'All rights reserved.',
    },
    // Team descriptions
    team: {
      timeo: 'Passionate about entrepreneurship and innovation for students.',
      nathan: 'Committed to creating practical solutions that make student life easier.',
      valentin: 'Determined to support every student towards academic success.',
    },
    // Feedback forms
    feedback: {
      reportProblemTitle: 'Report a problem',
      reportProblemDesc: 'Encountered a bug or malfunction? Describe it to us so we can improve.',
      suggestFeatureTitle: 'Suggest a feature',
      suggestFeatureDesc: 'Have an idea to improve the app? Share it with us!',
      emailLabel: 'Your email address',
      emailPlaceholder: 'example@email.com',
      problemLabel: 'Describe the problem encountered',
      problemPlaceholder: 'Describe the problem in detail: what were you doing, what happened, what was the expected result...',
      suggestionLabel: 'Describe your suggestion',
      suggestionPlaceholder: 'Describe your feature idea: what would it be used for, how do you imagine it...',
      sendButton: 'Send',
      sending: 'Sending...',
      successMessage: 'Thank you! Your message has been sent. We will respond quickly.',
      errorMessage: 'An error occurred. Please try again later.',
    },
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('fr')

  useEffect(() => {
    const savedLang = localStorage.getItem('studybox-language')
    if (savedLang && (savedLang === 'fr' || savedLang === 'en')) {
      setLanguage(savedLang)
    }
  }, [])

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('studybox-language', lang)
  }

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[language]
    for (const k of keys) {
      value = value?.[k]
    }
    return value || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
